language: ruby
dist: xenial
rvm:
- 2.3.8
- 2.4.6
- 2.5.5
- 2.6.3
- jruby-9.2.7.0
env:
  matrix:
  - SPHINX_VERSION=2.1.9 SPHINX_ENGINE=sphinx
  - SPHINX_VERSION=2.2.11 SPHINX_ENGINE=sphinx
  - SPHINX_VERSION=3.0.3 SPHINX_ENGINE=sphinx
  - SPHINX_VERSION=3.1.1 SPHINX_ENGINE=sphinx
  - SPHINX_VERSION=2.6.4 SPHINX_ENGINE=manticore
  - SPHINX_VERSION=2.7.5 SPHINX_ENGINE=manticore
  - SPHINX_VERSION=2.8.2 SPHINX_ENGINE=manticore
before_script:
- killall searchd; echo ''
- "./bin/loadsphinx $SPHINX_VERSION $SPHINX_ENGINE"
addons:
  apt:
    packages:
    - libodbc1
services:
  - mysql
before_install:
- gem update --system
after_script:
- killall searchd; echo ''
sudo: false
